# Generated by Django 6.0.5 on 2026-06-29 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("schedule", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Филиал клиники",
                "verbose_name_plural": "Филиалы клиник",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/avatars/"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "Пациент"),
                            ("doctor", "Врач"),
                            ("clinic", "Клиника"),
                            ("admin", "Администратор"),
                        ],
                        default="patient",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="ClinicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("clinic_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="clinics/logos/"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("schedule", models.JSONField(default=dict)),
                ("lunch_break", models.JSONField(default=dict)),
                ("emergency_24_7", models.BooleanField(default=False)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("reg_number", models.CharField(blank=True, max_length=100)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_date", models.DateField(blank=True, null=True)),
                ("license_authority", models.CharField(blank=True, max_length=255)),
                ("primary_specializations", models.JSONField(default=list)),
                ("narrow_specializations", models.JSONField(default=list)),
                ("additional_services", models.TextField(blank=True)),
                ("equipment", models.JSONField(default=list)),
                ("patient_conditions", models.JSONField(default=list)),
                ("payment_methods", models.JSONField(default=list)),
                ("agree_terms", models.BooleanField(default=False)),
                ("agree_privacy", models.BooleanField(default=False)),
                ("agree_data_processing", models.BooleanField(default=False)),
                ("agree_publishing", models.BooleanField(default=False)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("doctors_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("profile_views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль клиники",
                "verbose_name_plural": "Профили клиник",
            },
        ),
        migrations.CreateModel(
            name="ClinicPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="clinics/photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="users.clinicprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото клиники",
                "verbose_name_plural": "Фото клиник",
            },
        ),
        migrations.CreateModel(
            name="ClinicInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invites",
                        to="users.clinicbranch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="users.clinicprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инвайт клиники",
                "verbose_name_plural": "Инвайты клиник",
            },
        ),
        migrations.CreateModel(
            name="ClinicDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="clinics/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.clinicprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ клиники",
                "verbose_name_plural": "Документы клиник",
            },
        ),
        migrations.AddField(
            model_name="clinicbranch",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="users.clinicprofile",
            ),
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("languages", models.JSONField(default=list)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/photos/"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("schedule", models.JSONField(default=dict)),
                ("lunch_break", models.JSONField(blank=True, default=dict, null=True)),
                ("emergency_24_7", models.BooleanField(default=False)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("reg_number", models.CharField(blank=True, max_length=100)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_date", models.DateField(blank=True, null=True)),
                ("license_authority", models.CharField(blank=True, max_length=255)),
                ("primary_specializations", models.JSONField(default=list)),
                ("narrow_specializations", models.JSONField(default=list)),
                ("additional_services", models.TextField(blank=True)),
                ("equipment", models.JSONField(blank=True, default=list, null=True)),
                (
                    "patient_conditions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "payment_methods",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("agree_terms", models.BooleanField(default=False)),
                ("agree_privacy", models.BooleanField(default=False)),
                ("agree_data_processing", models.BooleanField(default=False)),
                ("agree_publishing", models.BooleanField(default=False)),
                ("about", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("is_online_available", models.BooleanField(default=False)),
                (
                    "consultation_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("education", models.JSONField(blank=True, default=list, null=True)),
                (
                    "work_experience",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("skills", models.JSONField(blank=True, default=list, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("profile_views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль врача",
                "verbose_name_plural": "Профили врачей",
            },
        ),
        migrations.CreateModel(
            name="DoctorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="doctors/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ врача",
                "verbose_name_plural": "Документы врача",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(blank=True, max_length=10)),
                ("allergies", models.JSONField(default=list)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пациента",
                "verbose_name_plural": "Профили пациентов",
            },
        ),
        migrations.CreateModel(
            name="DoctorClinicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_links",
                        to="users.clinicbranch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_links",
                        to="users.clinicprofile",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_links",
                        to="users.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь врача с клиникой",
                "verbose_name_plural": "Связи врачей с клиниками",
                "unique_together": {("doctor", "clinic")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("doctor", "Врач"),
                            ("clinic", "Клиника"),
                            ("service", "Услуга"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-created_at"],
                "unique_together": {("user", "target_type", "target_id")},
            },
        ),
    ]
