# Generated by Django 6.0.5 on 2026-06-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_remove_service_doctor"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="doctors", to="services.service"
            ),
        ),
    ]
