# Generated by Django 6.0.5 on 2026-05-24 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(default=list)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('schedule', models.JSONField(default=dict)),
                ('lunch_break', models.JSONField(default=dict)),
                ('emergency_24_7', models.BooleanField(default=False)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('reg_number', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_authority', models.CharField(blank=True, max_length=255)),
                ('primary_specializations', models.JSONField(default=list)),
                ('narrow_specializations', models.JSONField(default=list)),
                ('additional_services', models.TextField(blank=True)),
                ('equipment', models.JSONField(default=list)),
                ('patient_conditions', models.JSONField(default=list)),
                ('payment_methods', models.JSONField(default=list)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_privacy', models.BooleanField(default=False)),
                ('agree_data_processing', models.BooleanField(default=False)),
                ('agree_publishing', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('profile_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль врача',
                'verbose_name_plural': 'Профили врачей',
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doctors/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.doctorprofile')),
            ],
            options={
                'verbose_name': 'Документ врача',
                'verbose_name_plural': 'Документы врача',
            },
        ),
    ]
