# Generated by Django 6.0.5 on 2026-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0003_remove_user_middle_name_user_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_clinics',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='users.clinicprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_doctors',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_services',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='services.service'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
