# Generated by Django 6.0.5 on 2026-05-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_about_doctorprofile_consultation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('clinic', 'Клиника'), ('admin', 'Администратор')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinic_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('schedule', models.JSONField(default=dict)),
                ('lunch_break', models.JSONField(default=dict)),
                ('emergency_24_7', models.BooleanField(default=False)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('reg_number', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_authority', models.CharField(blank=True, max_length=255)),
                ('primary_specializations', models.JSONField(default=list)),
                ('narrow_specializations', models.JSONField(default=list)),
                ('additional_services', models.TextField(blank=True)),
                ('equipment', models.JSONField(default=list)),
                ('patient_conditions', models.JSONField(default=list)),
                ('payment_methods', models.JSONField(default=list)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_privacy', models.BooleanField(default=False)),
                ('agree_data_processing', models.BooleanField(default=False)),
                ('agree_publishing', models.BooleanField(default=False)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('doctors_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('profile_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль клиники',
                'verbose_name_plural': 'Профили клиник',
            },
        ),
        migrations.CreateModel(
            name='ClinicPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinics/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.clinicprofile')),
            ],
            options={
                'verbose_name': 'Фото клиники',
                'verbose_name_plural': 'Фото клиник',
            },
        ),
        migrations.CreateModel(
            name='ClinicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clinics/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.clinicprofile')),
            ],
            options={
                'verbose_name': 'Документ клиники',
                'verbose_name_plural': 'Документы клиник',
            },
        ),
    ]
