# Generated by Django 6.0.5 on 2026-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_clinicprofile_clinicphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
    ]
