# Generated by Django 6.0.5 on 2026-07-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode_phone_user_favorite_clinics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicdocument',
            options={'verbose_name': 'Документ клиники', 'verbose_name_plural': '↳ Документы клиник'},
        ),
        migrations.AlterModelOptions(
            name='clinicinvite',
            options={'verbose_name': 'Инвайт клиники', 'verbose_name_plural': '↳ Инвайты клиник'},
        ),
        migrations.AlterModelOptions(
            name='clinicphoto',
            options={'verbose_name': 'Фото клиники', 'verbose_name_plural': '↳ Фото клиник'},
        ),
        migrations.AlterModelOptions(
            name='doctorcliniclink',
            options={'verbose_name': 'Связь врача с клиникой', 'verbose_name_plural': '↳ Связи врачей с клиниками'},
        ),
        migrations.AlterModelOptions(
            name='doctordocument',
            options={'verbose_name': 'Документ врача', 'verbose_name_plural': '↳ Документы врача'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Код сброса пароля', 'verbose_name_plural': '↳ Коды сброса пароля'},
        ),
        migrations.AlterModelOptions(
            name='phoneverificationcode',
            options={'verbose_name': 'Код подтверждения телефона', 'verbose_name_plural': '↳ Коды подтверждения телефонов'},
        ),
    ]
