# Generated by Django 6.0.5 on 2026-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('users', '0005_alter_clinicdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='references.tag'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='references.tag'),
        ),
    ]
