# Generated by Django 6.0.5 on 2026-05-25 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('schedule', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.clinicprofile')),
            ],
            options={
                'verbose_name': 'Филиал клиники',
                'verbose_name_plural': 'Филиалы клиник',
            },
        ),
        migrations.CreateModel(
            name='ClinicInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='users.clinicbranch')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.clinicprofile')),
            ],
            options={
                'verbose_name': 'Инвайт клиники',
                'verbose_name_plural': 'Инвайты клиник',
            },
        ),
        migrations.CreateModel(
            name='DoctorClinicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_links', to='users.clinicbranch')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='users.clinicprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_links', to='users.doctorprofile')),
            ],
            options={
                'verbose_name': 'Связь врача с клиникой',
                'verbose_name_plural': 'Связи врачей с клиниками',
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
