# Generated by Django 6.0.5 on 2026-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="equipment",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="lunch_break",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="patient_conditions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="payment_methods",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="work_experience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
