# Generated by Django 6.0.5 on 2026-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_normalize_blank_phones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
