# Generated by Django 6.0.5 on 2026-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_phone_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "Пользователь с таким номером телефона уже зарегистрирован"
                },
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
