# Generated by Django 6.0.5 on 2026-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="academic_degree",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="additional_education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="position",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="qualification_category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
