# Generated by Django 6.0.5 on 2026-08-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_doctor_professional_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicprofile",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="tags",
        ),
    ]
