services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  web:
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn core.asgi:application \
          -k uvicorn.workers.UvicornWorker \
          --bind 0.0.0.0:8114 \
          --workers 2 \
          --timeout 120
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8114:8114"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped



volumes:
  redis_data:
  media_volume:
  static_volume:
