# Generated by Django 6.0.5 on 2026-06-30 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="doctor",
        ),
    ]
