# Generated by Django 6.0.5 on 2026-08-02 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_remove_service_doctor"),
        ("services", "0003_service_tags"),
    ]

    operations = []
