# Generated by Django 6.0.5 on 2026-08-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_merge_0003_remove_service_doctor_0003_service_tags"),
        ("users", "0018_doctor_professional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="users.clinicbranch",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="lunch_break",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/photos/"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
