# Generated by Django 6.0.5 on 2026-08-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_service_photo_branch_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="tags",
        ),
    ]
