# Generated by Django 6.0.5 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="recommendations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
