# Generated by Django 6.0.5 on 2026-09-22 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_aimessage_recommendations"),
        ("chat", "0003_chatmessage_edit_delete"),
    ]

    operations = []
