# Generated by Django 6.0.5 on 2026-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reply_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reply_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
