# Generated by Django 6.0.5 on 2026-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=255)),
                ("guest_phone", models.CharField(blank=True, max_length=20)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_online", models.BooleanField(default=False)),
                ("google_meet_link", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждён"),
                            ("cancelled", "Отменён"),
                            ("completed", "Завершён"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приём",
                "ordering": ["-created_at"],
            },
        ),
    ]
