# Generated by Django 6.0.5 on 2026-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="google_meet_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
