# Generated by Django 6.0.5 on 2026-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_consultation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
