# Generated by Django 6.0.5 on 2026-08-02 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointments",
            "0003_appointment_diagnosis_appointment_doctor_notes_and_more",
        ),
        ("appointments", "0004_appointment_ai_summary_and_more"),
    ]

    operations = []
