# Generated by Django 6.0.5 on 2026-08-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_merge_20260802_2322"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="egress_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="egress_status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="recording_url",
        ),
        migrations.AddField(
            model_name="appointment",
            name="ai_summary_docx_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_egress_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_egress_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_recording_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_egress_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_egress_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_recording_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
