from django.urls import path
from .views import (
    BranchListCreateView,
    BranchUpdateView,
    ClinicAppointmentListView,
    ClinicDoctorListView,
    ClinicDoctorDetailView,
    ClinicDoctorDocumentListCreateView,
    ClinicDoctorDocumentDeleteView,
    ClinicProfileView,
    ClinicReviewListView,
    ClinicServiceDetailView,
    ClinicServiceListCreateView,
    ClinicStatsView,
    InviteDeleteView,
    InviteListCreateView,
    ClinicPhotoListCreateView,
    ClinicPhotoDeleteView,
    ClinicDocumentListCreateView,
    ClinicDocumentDeleteView,
)

urlpatterns = [
    path('profile/', ClinicProfileView.as_view(), name='clinic-own-profile'),
    path('appointments/', ClinicAppointmentListView.as_view(), name='clinic-appointments'),
    path('stats/', ClinicStatsView.as_view(), name='clinic-stats'),
    path('reviews/', ClinicReviewListView.as_view(), name='clinic-reviews'),
    path('doctors/', ClinicDoctorListView.as_view(), name='clinic-doctors'),
    path('doctors/<int:pk>/', ClinicDoctorDetailView.as_view(), name='clinic-doctor-detail'),
    path('doctors/<int:pk>/documents/', ClinicDoctorDocumentListCreateView.as_view(), name='clinic-doctor-documents'),
    path('doctors/<int:pk>/documents/<int:doc_id>/', ClinicDoctorDocumentDeleteView.as_view(), name='clinic-doctor-document-delete'),
    path('services/', ClinicServiceListCreateView.as_view(), name='clinic-services'),
    path('services/<int:pk>/', ClinicServiceDetailView.as_view(), name='clinic-service-detail'),
    path('branches/', BranchListCreateView.as_view(), name='clinic-branch-list-create'),
    path('branches/<int:pk>/', BranchUpdateView.as_view(), name='clinic-branch-update'),
    path('invites/', InviteListCreateView.as_view(), name='clinic-invite-list-create'),
    path('invites/<uuid:pk>/', InviteDeleteView.as_view(), name='clinic-invite-delete'),
    path('photos/', ClinicPhotoListCreateView.as_view(), name='clinic-photos'),
    path('photos/<int:pk>/', ClinicPhotoDeleteView.as_view(), name='clinic-photo-delete'),
    path('documents/', ClinicDocumentListCreateView.as_view(), name='clinic-documents'),
    path('documents/<int:pk>/', ClinicDocumentDeleteView.as_view(), name='clinic-document-delete'),
]
