# Generated by Django 6.0.5 on 2026-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
                "ordering": ["name"],
            },
        ),
    ]
