# Generated by Django 6.0.5 on 2026-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0002_add_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialization",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="specializations/photos/"
            ),
        ),
    ]
