# Generated by Django 6.0.5 on 2026-08-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0003_specialization_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="X (Twitter)"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "terms_text",
                    models.TextField(blank=True, verbose_name="Условия и положения"),
                ),
                (
                    "privacy_policy_text",
                    models.TextField(
                        blank=True, verbose_name="Политика конфиденциальности"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
