# Generated by Django 6.0.5 on 2026-08-12 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0004_site_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название статуса"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="account_statuses/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание статуса"
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Процент качества профиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус аккаунта",
                "verbose_name_plural": "Статусы аккаунтов",
                "ordering": ["name"],
            },
        ),
    ]
