# Generated by Django 6.0.5 on 2026-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0005_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_doctor_photo_processing_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Если выключено — ?process_photo=true у PUT /api/doctor/profile/ ничего не делает, фото сохраняется как есть.",
                verbose_name="ИИ-обработка фото врачей включена",
            ),
        ),
    ]
