# Generated by Django 6.0.5 on 2026-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0006_ai_photo_toggle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ai_photo_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI (gpt-image-1)"),
                    ("gemini", "Gemini (nano banana)"),
                ],
                default="openai",
                max_length=10,
                verbose_name="Провайдер ИИ-обработки фото",
            ),
        ),
    ]
