# Generated by Django 6.0.5 on 2026-08-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0007_ai_photo_provider"),
        ("services", "0006_remove_tags"),
        ("users", "0019_remove_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
