# Generated by Django 6.0.5 on 2026-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_appointment_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("appointment_reminder", "Напоминание о записи"),
                    ("appointment_created", "Новая запись"),
                    ("appointment_confirmed", "Запись подтверждена"),
                    ("appointment_cancelled", "Запись отменена"),
                    ("appointment_completed", "Приём завершён"),
                    ("new_review", "Новый отзыв"),
                    ("new_message", "Новое сообщение"),
                    ("clinic_invite_received", "Приглашение от клиники"),
                    ("clinic_invite_accepted", "Приглашение принято"),
                    ("clinic_invite_declined", "Приглашение отклонено"),
                    ("system", "Системное"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
